package com.example.y.mvp;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.y.mvp.ImageDetailInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_DETAIL_INFO".
*/
public class ImageDetailInfoDao extends AbstractDao<ImageDetailInfo, Void> {

    public static final String TABLENAME = "IMAGE_DETAIL_INFO";

    /**
     * Properties of entity ImageDetailInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "id", false, "ID");
        public final static Property Gallery = new Property(1, Integer.class, "gallery", false, "GALLERY");
        public final static Property Src = new Property(2, String.class, "src", false, "SRC");
    };


    public ImageDetailInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ImageDetailInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_DETAIL_INFO\" (" + //
                "\"ID\" INTEGER," + // 0: id
                "\"GALLERY\" INTEGER," + // 1: gallery
                "\"SRC\" TEXT);"); // 2: src
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_DETAIL_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ImageDetailInfo entity) {
        stmt.clearBindings();
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer gallery = entity.getGallery();
        if (gallery != null) {
            stmt.bindLong(2, gallery);
        }
 
        String src = entity.getSrc();
        if (src != null) {
            stmt.bindString(3, src);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public ImageDetailInfo readEntity(Cursor cursor, int offset) {
        ImageDetailInfo entity = new ImageDetailInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // gallery
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // src
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ImageDetailInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setGallery(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setSrc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(ImageDetailInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(ImageDetailInfo entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
