package com.example.y.mvp;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.y.mvp.ImageListInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_LIST_INFO".
*/
public class ImageListInfoDao extends AbstractDao<ImageListInfo, Void> {

    public static final String TABLENAME = "IMAGE_LIST_INFO";

    /**
     * Properties of entity ImageListInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Integer.class, "id", false, "ID");
        public final static Property Galleryclass = new Property(1, Integer.class, "galleryclass", false, "GALLERYCLASS");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Img = new Property(3, String.class, "img", false, "IMG");
        public final static Property Count = new Property(4, Integer.class, "count", false, "COUNT");
        public final static Property Rcount = new Property(5, Integer.class, "rcount", false, "RCOUNT");
        public final static Property Fcount = new Property(6, Integer.class, "fcount", false, "FCOUNT");
        public final static Property Size = new Property(7, Integer.class, "size", false, "SIZE");
    };


    public ImageListInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ImageListInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_LIST_INFO\" (" + //
                "\"ID\" INTEGER," + // 0: id
                "\"GALLERYCLASS\" INTEGER," + // 1: galleryclass
                "\"TITLE\" TEXT," + // 2: title
                "\"IMG\" TEXT," + // 3: img
                "\"COUNT\" INTEGER," + // 4: count
                "\"RCOUNT\" INTEGER," + // 5: rcount
                "\"FCOUNT\" INTEGER," + // 6: fcount
                "\"SIZE\" INTEGER);"); // 7: size
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_LIST_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ImageListInfo entity) {
        stmt.clearBindings();
 
        Integer id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer galleryclass = entity.getGalleryclass();
        if (galleryclass != null) {
            stmt.bindLong(2, galleryclass);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(4, img);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(5, count);
        }
 
        Integer rcount = entity.getRcount();
        if (rcount != null) {
            stmt.bindLong(6, rcount);
        }
 
        Integer fcount = entity.getFcount();
        if (fcount != null) {
            stmt.bindLong(7, fcount);
        }
 
        Integer size = entity.getSize();
        if (size != null) {
            stmt.bindLong(8, size);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public ImageListInfo readEntity(Cursor cursor, int offset) {
        ImageListInfo entity = new ImageListInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // galleryclass
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // img
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // count
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // rcount
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // fcount
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // size
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ImageListInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setGalleryclass(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCount(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRcount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setFcount(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setSize(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(ImageListInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(ImageListInfo entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
