package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS_TAB_NAME_INFO".
 */
public class NewsTabNameInfo {

    private Integer id;
    private String name;

    public NewsTabNameInfo() {
    }

    public NewsTabNameInfo(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
