package com.example.y.mvp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS_LIST_INFO".
 */
public class NewsListInfo {

    private Integer id;
    private Integer type;
    private Integer count;
    private String description;
    private Integer fcount;
    private String fromname;
    private String title;
    private String img;
    private String fromurl;
    private Long time;
    private String keywords;

    public NewsListInfo() {
    }

    public NewsListInfo(Integer id, Integer type, Integer count, String description, Integer fcount, String fromname, String title, String img, String fromurl, Long time, String keywords) {
        this.id = id;
        this.type = type;
        this.count = count;
        this.description = description;
        this.fcount = fcount;
        this.fromname = fromname;
        this.title = title;
        this.img = img;
        this.fromurl = fromurl;
        this.time = time;
        this.keywords = keywords;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getFcount() {
        return fcount;
    }

    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    public String getFromname() {
        return fromname;
    }

    public void setFromname(String fromname) {
        this.fromname = fromname;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public String getFromurl() {
        return fromurl;
    }

    public void setFromurl(String fromurl) {
        this.fromurl = fromurl;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

}
